[build]
  command = "npm run build"
  publish = "lib"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 5173

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[headers]
  # Cache static assets
  "/build/*" = {
    Cache-Control = "public, max-age=31536000, immutable"
  }
  
  # Cache fonts
  "/fonts/*" = {
    Cache-Control = "public, max-age=31536000, immutable"
  }

  # Security headers
  "/*" = {
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
  }