[build]
  command = "npm run build"
  publish = "lib"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 5173

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
